### ISSUE TITLE
Productos sin actualizacion

### ISSUE THREAD

**Issue by scornejob** [Data-Observatory/covid19-API#33]
nuevamente, hay un problema desde el 15 de agosto

**Comment by scornejob** [comment]
```
Checking prod19: https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto19/CasosActivosPorComuna_std.csv
Traceback (most recent call last):
['Region', 'Codigo region', 'Comuna', 'Codigo comuna', 'Poblacion', 'Fecha', 'Casos activos']
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1858, in objects_to_datetime64ns
Checking prod20: https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto20/NumeroVentiladores_std.csv
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
['Ventiladores', 'fecha', 'numero']
TypeError: Unrecognized value type: <class 'str'>
```

**Comment by scornejob** [comment]
Encontré otro problema con una fecha en https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto44/EgresosHospitalarios_std.csv 
`S03-04_03-08,2020-08-15.1,4.0`

**Comment by scornejob** [comment]
La fecha estaba repetida en el spreadsheet. Esta corregida, pero es necesario pushear al master de Minciencia cuando se publique el informe diario.

**Comment by scornejob** [comment]
Generé los productos localmente, para estar al día. Voy a mentener este issue abierto hasta que el actions los genere automaticamente.

**Comment by scornejob** [comment]
Corrió bien https://github.com/Data-Observatory/covid19-API/runs/1008509045?check_suite_focus=true. Cierro el issue.
